# Generated by Django 4.1 on 2024-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_interview', models.DateTimeField(verbose_name='面談日付')),
                ('name_of_company', models.CharField(max_length=200, verbose_name='会社名')),
                ('what_kinda_spi', models.TextField(verbose_name='適性検査種類')),
                ('date_of_spi', models.DateTimeField(verbose_name='適性検査日付')),
                ('resume_of_spi', models.DateTimeField(verbose_name='履歴書提出日時')),
                ('detail_text', models.TextField(verbose_name='詳細')),
            ],
        ),
    ]
