# Generated by Django 4.1 on 2024-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='what_kinda_spi',
            field=models.CharField(max_length=100, verbose_name='適性検査種類'),
        ),
    ]
