# Generated by Django 5.1 on 2024-10-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0004_alter_day_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='day',
            name='detail_text',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
    ]
